//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVCEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class informacionTrabajadores
    {
        public int IDEMPLEADO { get; set; }
        public string APELLIDO { get; set; }
        public string CARGO { get; set; }
        public Nullable<int> SALARIO { get; set; }
    }
}
