//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoTutorial.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOSPITALEntities1 : DbContext
    {
        public HOSPITALEntities1()
            : base("name=HOSPITALEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EQUIPO> EQUIPO { get; set; }
        public virtual DbSet<JUGADORES> JUGADORES { get; set; }
        public virtual DbSet<InformacionJugadores> InformacionJugadores { get; set; }
    }
}
