//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoTutorial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionJugadores
    {
        public int IDEMJUGADOR { get; set; }
        public string JNOMBRE { get; set; }
        public string NOM_EQUIPO { get; set; }
        public string CIUDAD { get; set; }
    }
}
