//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoTutorial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUGADORES
    {
        public int NUM_JUGADORE { get; set; }
        public Nullable<int> NUM_EQUIPO { get; set; }
        public string JNOMBRE { get; set; }
    }
}
